# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from TicTacToe.src.gui import window

if __name__ == '__main__':

    window.mainloop()